server:
    port: 8889
#    ssl:
#        key-store: classpath:7340916_tenero.cn.pfx
#        key-store-type: PKCS12
#        key-store-password: MKnkcKPP
#        enabled: true
#    servlet:
#        session:
#            cookie:
#                http-only: true
#                secure: true

spring:
    #连接mysql
    datasource:
        url: jdbc:mysql://39.107.127.19:3306/tenero_blog?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
    # redis
    redis:
        host: 39.107.127.19
        port: 6379
        password: 1998816
        database: 0
        #连接超时时间（毫秒）
        timeout: 5000s
        jedis:
            pool:
                #连接池最大连接数
                max-active: 8
                #最小空闲链接
                min-idle: 0
                #最大空闲链接
                max-idle: 8
                #连接池最大阻塞等待时间（附属标识没有限制）
                max-wait: -1ms

    # mongodb
    data:
        mongodb:
            uri: mongodb://root:tenero1998@39.107.127.19:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
            database: blogs


        # elasticsearch
        elasticsearch:
            repositories:
                enabled: true


#mybatis
mybatis:
    mapper-locations: classpath*:/mappers/**/*Mapper.xml


# 指定log4j2作为日志
#logging:
#  config: classpath:log4j2.xml
#  level:
#    com.tenero.blogs.mapper: DEBUG


# 操作OSS
oss:
    AccessKeyID: LTAI5tHZVxExj2Rnmjn6P3Sv
    AccessKeySecret: AvRGq6UIQf7CGJvirYuaIYKtYZ1JAn
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: tenero-blog
    MusicfirstKey: music/
    ImagefirstKey: img/
# 盐
salt: tenero_kesong